# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_menu_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='fecha',
            new_name='date',
        ),
    ]
