# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_auto_20171116_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_menu',
            name='option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='delivery_app.Options'),
            preserve_default=False,
        ),
    ]
